kind: pipeline
type: docker
name: default

steps:
  - name: getTimestamp
    image: debian:buster-slim
    commands:
      - echo -n "$(date +%Y-%m-%d-%H%M).${DRONE_COMMIT_SHA:0:7},latest" > .tags

  - name: dockerBuildPush
    image: plugins/docker
    settings:
      repo: kghf/simple-dash
      username: larskghf
      password:
        from_secret: docker_password
      build_args:
        - SIMPLE_DASH_DL_URL=https://github.com/kutyla-philipp/simple-dash/archive/master.zip

trigger:
  branch:
    - master