kind: pipeline
type: docker
name: branch

steps:
  - name: getTimestamp
    image: debian:buster-slim
    commands:
      - echo -n "$(date +%Y-%m-%d).${DRONE_COMMIT_SHA:0:8},latest" > .tags
  - name: dockerBuild
    image: plugins/docker
    settings:
      repo: kghf/simple-dash
      dry_run: true
      build_args:
        - SIMPLE_DASH_DL_URL=https://github.com/kutyla-philipp/simple-dash/archive/master.zip

trigger:
  branch:
    - feature/*

---
kind: pipeline
type: docker
name: buildPush

steps:
  - name: getTimestamp
    image: debian:buster-slim
    commands:
      - echo -n "$(date +%Y-%m-%d).${DRONE_COMMIT_SHA:0:8},latest" > .tags
  - name: dockerBuildPush
    image: plugins/docker
    settings:
      repo: kghf/simple-dash
      username: larskghf
      password:
        from_secret: docker_password
      build_args:
        - SIMPLE_DASH_DL_URL=https://github.com/kutyla-philipp/simple-dash/archive/master.zip
  - name: updateDockerReadme
    image: kghf/dockerhub-readme-updater:latest
    environment:
      DOCKER_REPO: kghf/simple-dash
      DOCKER_USERNAME: larskghf
      DOCKER_PASSWORD:
        from_secret: docker_password

trigger:
  branch:
    - master