kind: pipeline
name: default

steps:
  - name: getTimestamp
    image: debian:buster-slim
    commands:
      - export timestamp=$(date +%Y-%m-%d-%H%M)
      - echo -n "${timestamp}.${DRONE_COMMIT_SHA:0:7},latest" > .tags


  - name: dockerBuildPush
    image: plugins/docker
    settings:
      repo: larskghf/bar
      username: larskghf
      password:
        from_secret: docker_password
      build_args:
        - SIMPLE_DASH_DL_URL=https://github.com/kutyla-philipp/simple-dash/archive/master.zip